version: '3.9'

services:
  app:
    image: 'library-application:latest'
    environment:
      - "SPRING_PROFILES_ACTIVE=demo"
    build:
      context: .
    ports:
      - "2703:2703"
    networks:
      - library-network
networks:
  library-network: